import { NextResponse } from "next/server";
import { guestbook } from "../store";

/**
 * Your controls for the guestbook, used by the private page at
 * `/guestbook/admin`. Not linked from anywhere.
 *
 *   GET  /api/feedback/moderate                 every note, hidden ones too
 *   POST /api/feedback/moderate { action, id }  action: "hide" | "show" | "delete"
 *
 * Both need the header `x-admin-key` to equal the Netlify environment
 * variable `FEEDBACK_ADMIN_KEY`. With that variable unset, this route does not
 * exist. Changes are POSTs so that no link, preview or crawler can ever
 * delete a note by visiting a URL.
 */

export const dynamic = "force-dynamic";

const NOTE_PREFIX = "notes/";

interface StoredNote {
  id: string;
  text: string;
  at: string;
  hidden?: boolean;
}

function check(request: Request): NextResponse | null {
  const secret = process.env.FEEDBACK_ADMIN_KEY;
  if (!secret) return NextResponse.json({ error: "not found" }, { status: 404 });
  if (request.headers.get("x-admin-key") !== secret) {
    return NextResponse.json({ error: "wrong key" }, { status: 403 });
  }
  return null;
}

async function allNotes(): Promise<StoredNote[]> {
  const store = guestbook();
  const keys = (await store.list(NOTE_PREFIX)).sort().reverse();
  const notes: StoredNote[] = [];
  for (const key of keys) {
    const note = (await store.getJSON<StoredNote>(key))?.data;
    if (note) notes.push(note);
  }
  return notes;
}

export async function GET(request: Request) {
  const denied = check(request);
  if (denied) return denied;
  return NextResponse.json({ notes: await allNotes() }, { headers: { "Cache-Control": "no-store" } });
}

export async function POST(request: Request) {
  const denied = check(request);
  if (denied) return denied;

  let body: { action?: unknown; id?: unknown };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "bad request" }, { status: 400 });
  }

  const id = typeof body.id === "string" ? body.id : "";
  // Ids are generated by the API: a timestamp and a short random tail.
  if (!/^[\w-]{10,80}$/.test(id)) return NextResponse.json({ error: "bad id" }, { status: 400 });

  const store = guestbook();
  const key = NOTE_PREFIX + id;
  const current = await store.getJSON<StoredNote>(key);
  if (!current) return NextResponse.json({ error: "no such note" }, { status: 404 });

  if (body.action === "delete") {
    await store.remove(key);
  } else if (body.action === "hide" || body.action === "show") {
    await store.setJSON(key, { ...current.data, hidden: body.action === "hide" }, current.etag);
  } else {
    return NextResponse.json({ error: "unknown action" }, { status: 400 });
  }

  return NextResponse.json({ notes: await allNotes() });
}
